kind: "Trusti"
apiVersion: "org.trusti/v1"
metadata:
  name: test-app
spec:
  db:
    size: "0.5Gi"
    resourceLimits:
      cpuRequest: "0.1"
      cpuLimit: "0.5"
      memoryRequest: "0.1Gi"
      memoryLimit: "0.5Gi"
  apiResourceLimits:
    cpuRequest: "0.1"
    cpuLimit: "2"
    memoryRequest: "0.1Gi"
    memoryLimit: "2Gi"
